# Generated by Django 2.1.7 on 2019-05-14 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='/media/profile/default.jpg', null=True, upload_to='')),
                ('cover_image', models.ImageField(default='/ngo/default.jpg', null=True, upload_to='')),
                ('profile_bio', models.CharField(default=None, max_length=1000, null=True)),
                ('registration_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=30, null=True)),
                ('address', models.CharField(default=None, max_length=1000, null=True)),
                ('city', models.CharField(default=None, max_length=200, null=True)),
                ('work_domain', models.CharField(default='Public Welfare', max_length=400, null=True)),
                ('country', models.CharField(default=None, max_length=200, null=True)),
                ('rating', models.FloatField(default=0.0, null=True)),
                ('funding_status', models.CharField(default=None, max_length=50, null=True)),
                ('ngo_slogan', models.CharField(max_length=200, null=True)),
                ('ngo_description', models.CharField(default=None, max_length=10000, null=True)),
                ('established_year', models.DateField(default=None, null=True)),
                ('website', models.CharField(max_length=300, null=True)),
                ('founded_by', models.CharField(max_length=200, null=True)),
                ('beneficiary_facility', models.CharField(max_length=700, null=True)),
                ('account_holder_name', models.CharField(default=None, max_length=100, null=True)),
                ('account_number', models.IntegerField(default=0, null=True)),
                ('IFSC_code', models.CharField(default=None, max_length=50, null=True)),
                ('branch_name', models.CharField(default=None, max_length=100, null=True)),
                ('verified', models.CharField(default='not verified', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ngo',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo_app.State'),
        ),
        migrations.AddField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
