# Generated by Django 2.1.7 on 2019-03-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='relation_type',
            field=models.CharField(default='connection', max_length=100, null=True),
        ),
    ]
