# Generated by Django 2.1.7 on 2019-04-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_auto_20190418_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_by_ngo',
        ),
    ]
