# Generated by Django 2.1.7 on 2019-04-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_remove_post_posted_by_ngo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_by_con',
            new_name='posted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted_user_image',
        ),
    ]
